project:
  type: website
  output-dir: docs

website:
  title: "M2-GENIOMHE PROJECT"
  page-navigation: false
  navbar:
    background: "#265073"
    search: false
    left:
      - text: "Description"
        file: "index.qmd"
      - text: "Guidelines"
        file: "pages/guideline.qmd"
      - text: "Contact"
        file: "pages/contact.qmd"
  page-footer: "Copyright 2024, Clément Bernard" 
format:
  html:
    theme: flatly
    css: styles.css
    toc: true
    page-layout: full